networks:
  yrn:
    driver: bridge

services:
  consul:
    image: hashicorp/consul
    networks:
      - yrn
    ports:
      - "8500:8500"
    command: ["agent", "-dev", "-client=0.0.0.0"]

  agent:
    image: ghcr.io/yrn-go/yrn:latest
    command: ["/app/agent"]
    environment:
      CONSUL_HTTP_ADDR: http://consul:8500
      CONNECTOR_SERVICE_NAME: connector
      SERVICE_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - yrn
    depends_on:
      - consul

  connector:
    image: ghcr.io/yrn-go/yrn:latest
    command: ["/app/connector"]
    environment:
      CONSUL_HTTP_ADDR: http://consul:8500
      SERVICE_NAME: connector
      SERVICE_HOST: connector
      SERVICE_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - yrn
    depends_on:
      - consul