apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: my-app
          image: ghcr.io/yrn-go/yrn:latest
          ports:
            - containerPort: 8080
