apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  namespace: yrn-api
  labels:
    app: my-app
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 10m }
        - setWeight: 50
        - pause: { duration: 10m }
        - setWeight: 100
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: my-app
          image: ghcr.io/yrn-go/yrn:latest
          command: ["/app/api"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: yrn-api
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 8080
---
