name: Go Tests & Docker Build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Create Test Workspace
        run: |
          mkdir -p /home/runner/test_workspace
          cp -r . /home/runner/test_workspace/

      - name: Run Tests
        working-directory: /home/runner/test_workspace
        run: |
          go mod tidy
          go test ./... -v

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'  # Só roda se for um push na branch 'main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Short Commit Hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short=5 HEAD)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          docker build -t $IMAGE_NAME:${{ env.commit_hash }} -t $IMAGE_NAME:latest .

      - name: Push Docker Image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}
          docker push $IMAGE_NAME:${{ env.commit_hash }}
          docker push $IMAGE_NAME:latest

      - name: Update Rollout Image Tag
        run: |
          sed -i "s|image: ghcr.io/lffranca/yrn:.*|image: ghcr.io/lffranca/yrn:${{ env.commit_hash }}|" infra/apps/api/deployment.yaml

      - name: Commit and Push Updated Rollout
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add infra/apps/api/deployment.yaml
          git commit -m "chore: update rollout image to ${{ env.commit_hash }}"
          git push
